active_dc1394: []
active_gige: [Front_GigE, Bottom_GigE]
active_webcam: false
bottom1_image:
  compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
  theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
Front_GigE_auto_brightness_auto: true
Front_GigE_auto_brightness_target: 50
Front_GigE_auto_brightness_target_variation: 16
Front_GigE_auto_brightness_variation: 16
Front_GigE_exposure: 573.0
Front_GigE_exposure_auto: true
Front_GigE_format: 17301513
Front_GigE_framerate: 15
Front_GigE_gain: 1.0
Front_GigE_gain_auto: true
Front_GigE_gamma: 0
Front_GigE_guid: '1230819763'
Front_GigE_height: 1544
Front_GigE_name: Front_GigE
Front_GigE_saturation: 0
Front_GigE_shutter: 32.0
Front_GigE_shutter_auto: false
Front_GigE_white_balance_auto: false 
Front_GigE_white_balance_blue: 1.6015625
Front_GigE_white_balance_execute: false
Front_GigE_white_balance_green: 1.0
Front_GigE_white_balance_red: 2.296875
Front_GigE_whitebalance_blue: 1.6015625
Front_GigE_whitebalance_execute: false
Front_GigE_whitebalance_green: 1.0
Front_GigE_whitebalance_red: 2.296875
Front_GigE_width: 2064
Front_GigE_x_offset: 0
Front_GigE_y_offset: 0
Bottom_GigE_auto_brightness_auto: true
Bottom_GigE_auto_brightness_target: 50
Bottom_GigE_auto_brightness_target_variation: 16
Bottom_GigE_auto_brightness_variation: 16
Bottom_GigE_exposure: 573.0
Bottom_GigE_exposure_auto: true
Bottom_GigE_format: 17301513
Bottom_GigE_framerate: 15
Bottom_GigE_gain: 1.0
Bottom_GigE_gain_auto: true
Bottom_GigE_gamma: 0
Bottom_GigE_guid: '1230819763'
Bottom_GigE_height: 1544
Bottom_GigE_name: Bottom_GigE
Bottom_GigE_saturation: 0
Bottom_GigE_shutter: 32.0
Bottom_GigE_shutter_auto: false
Bottom_GigE_white_balance_auto: false 
Bottom_GigE_white_balance_blue: 1.6015625
Bottom_GigE_white_balance_execute: false
Bottom_GigE_white_balance_green: 1.0
Bottom_GigE_white_balance_red: 2.296875
Bottom_GigE_whitebalance_blue: 1.6015625
Bottom_GigE_whitebalance_execute: false
Bottom_GigE_whitebalance_green: 1.0
Bottom_GigE_whitebalance_red: 2.296875
Bottom_GigE_width: 2064
Bottom_GigE_x_offset: 0
Bottom_GigE_y_offset: 0
front_image:
  compressed: {format: jpeg, jpeg_quality: 80, png_level: 9}
  theora: {keyframe_frequency: 64, optimize_for: 1, quality: 31, target_bitrate: 800000}
