# File containing all the initial camera parameters for the default camera.

# Parameters for the Front Guppy Camera
/provider_vision/camera_parameters/front_guppy/name: "Front Guppy"
/provider_vision/camera_parameters/front_guppy/guid: "2892819690326160"
/provider_vision/camera_parameters/front_guppy/framerate: 0
/provider_vision/camera_parameters/front_guppy/gain_manual: true
/provider_vision/camera_parameters/front_guppy/shutter_manual: true
/provider_vision/camera_parameters/front_guppy/white_balance_manual: true
/provider_vision/camera_parameters/front_guppy/gain: 0.0
/provider_vision/camera_parameters/front_guppy/shutter: 32.0
/provider_vision/camera_parameters/front_guppy/gamma: 0
/provider_vision/camera_parameters/front_guppy/exposure: 0
/provider_vision/camera_parameters/front_guppy/white_balance_red: 568.0
/provider_vision/camera_parameters/front_guppy/white_balance_blue: 381.0
/provider_vision/camera_parameters/front_guppy/saturation: 0
/provider_vision/camera_parameters/front_guppy/gamma_i_state: 0.0
/provider_vision/camera_parameters/front_guppy/gamma_i_min: 1.0
/provider_vision/camera_parameters/front_guppy/gamma_i_max: 20
/provider_vision/camera_parameters/front_guppy/gamma_i_gain: 1
/provider_vision/camera_parameters/front_guppy/gamma_p_gain: 0.5
/provider_vision/camera_parameters/front_guppy/gamma_d_gain: 0.75
/provider_vision/camera_parameters/front_guppy/gain_i_state: 0.0
/provider_vision/camera_parameters/front_guppy/gain_i_min: 1.0
/provider_vision/camera_parameters/front_guppy/gain_i_max: 200
/provider_vision/camera_parameters/front_guppy/gain_i_gain: 1
/provider_vision/camera_parameters/front_guppy/gain_p_gain: 0.5
/provider_vision/camera_parameters/front_guppy/gain_d_gain: 0.75
/provider_vision/camera_parameters/front_guppy/exposure_i_state: 0.0
/provider_vision/camera_parameters/front_guppy/exposure_i_min: 1.0
/provider_vision/camera_parameters/front_guppy/exposure_i_max: 200
/provider_vision/camera_parameters/front_guppy/exposure_i_gain: 1
/provider_vision/camera_parameters/front_guppy/exposure_p_gain: 0.5
/provider_vision/camera_parameters/front_guppy/exposure_d_gain: 0.75
/provider_vision/camera_parameters/front_guppy/saturation_i_state: 0.0
/provider_vision/camera_parameters/front_guppy/saturation_i_min: 1.0
/provider_vision/camera_parameters/front_guppy/saturation_i_max: 200
/provider_vision/camera_parameters/front_guppy/saturation_i_gain: 1
/provider_vision/camera_parameters/front_guppy/saturation_p_gain: 0.5
/provider_vision/camera_parameters/front_guppy/saturation_d_gain: 0.75

# Parameters for the Bottom Guppy Camera
/provider_vision/camera_parameters/bottom_guppy/name: "Bottom Guppy"
/provider_vision/camera_parameters/bottom_guppy/guid: "582164340023517285"
/provider_vision/camera_parameters/bottom_guppy/framerate: 0
/provider_vision/camera_parameters/bottom_guppy/gain_manual: true
/provider_vision/camera_parameters/bottom_guppy/shutter_manual: true
/provider_vision/camera_parameters/bottom_guppy/white_balance_manual: true
/provider_vision/camera_parameters/bottom_guppy/gain: 1.0
/provider_vision/camera_parameters/bottom_guppy/shutter: 32.0
/provider_vision/camera_parameters/bottom_guppy/gamma: 0
/provider_vision/camera_parameters/bottom_guppy/exposure: 95
/provider_vision/camera_parameters/bottom_guppy/saturation: 0
/provider_vision/camera_parameters/bottom_guppy/white_balance_red: 568.0
/provider_vision/camera_parameters/bottom_guppy/white_balance_blue: 381.0
/provider_vision/camera_parameters/bottom_guppy/gamma_i_state: 0.0
/provider_vision/camera_parameters/bottom_guppy/gamma_i_min: 1.0
/provider_vision/camera_parameters/bottom_guppy/gamma_i_max: 20
/provider_vision/camera_parameters/bottom_guppy/gamma_i_gain: 1
/provider_vision/camera_parameters/bottom_guppy/gamma_p_gain: 0.5
/provider_vision/camera_parameters/bottom_guppy/gamma_d_gain: 0.75
/provider_vision/camera_parameters/bottom_guppy/gain_i_state: 0.0
/provider_vision/camera_parameters/bottom_guppy/gain_i_min: 1.0
/provider_vision/camera_parameters/bottom_guppy/gain_i_max: 200
/provider_vision/camera_parameters/bottom_guppy/gain_i_gain: 1
/provider_vision/camera_parameters/bottom_guppy/gain_p_gain: 0.5
/provider_vision/camera_parameters/bottom_guppy/gain_d_gain: 0.75
/provider_vision/camera_parameters/bottom_guppy/exposure_i_state: 0.0
/provider_vision/camera_parameters/bottom_guppy/exposure_i_min: 1.0
/provider_vision/camera_parameters/bottom_guppy/exposure_i_max: 200
/provider_vision/camera_parameters/bottom_guppy/exposure_i_gain: 1
/provider_vision/camera_parameters/bottom_guppy/exposure_p_gain: 0.5
/provider_vision/camera_parameters/bottom_guppy/exposure_d_gain: 0.75
/provider_vision/camera_parameters/bottom_guppy/saturation_i_state: 0.0
/provider_vision/camera_parameters/bottom_guppy/saturation_i_min: 1.0
/provider_vision/camera_parameters/bottom_guppy/saturation_i_max: 200
/provider_vision/camera_parameters/bottom_guppy/saturation_i_gain: 1
/provider_vision/camera_parameters/bottom_guppy/saturation_p_gain: 0.5
/provider_vision/camera_parameters/bottom_guppy/saturation_d_gain: 0.75


# Parameters for the all other camera (default configurations)
/provider_vision/camera_parameters/default/name: "Default Camera"
/provider_vision/camera_parameters/default/framerate: 0
/provider_vision/camera_parameters/default/gain_manual: true
/provider_vision/camera_parameters/default/shutter_manual: true
/provider_vision/camera_parameters/default/white_balance_manual: true
/provider_vision/camera_parameters/default/gain: 350.0
/provider_vision/camera_parameters/default/shutter: 500.0
/provider_vision/camera_parameters/default/gamma: 0
/provider_vision/camera_parameters/default/exposure: 0
/provider_vision/camera_parameters/default/white_balance_red: 511.0
/provider_vision/camera_parameters/default/white_balance_blue: 412.0
