active_dc1394: [front_guppy, bottom_guppy]
active_gige: [bottom_gige]
active_webcam: false
bottom_gige_auto_brightness_auto: false
bottom_gige_auto_brightness_target: 100
bottom_gige_auto_brightness_target_variation: 16
bottom_gige_auto_brightness_variation: 16
bottom_gige_exposure: 1000.0
bottom_gige_exposure_auto: false
bottom_gige_format: 17301513
bottom_gige_framerate: 15
bottom_gige_gain: 1.0
bottom_gige_gain_auto: false
bottom_gige_gamma: 0
bottom_gige_guid: '1230819763'
bottom_gige_height: 780
bottom_gige_name: bottom_gige
bottom_gige_saturation: 0
bottom_gige_shutter: 32.0
bottom_gige_shutter_auto: false
bottom_gige_white_balance_auto: true
bottom_gige_white_balance_blue: 381.0
bottom_gige_white_balance_red: 568.0
bottom_gige_whitebalance_blue: 1.0
bottom_gige_whitebalance_execute: true
bottom_gige_whitebalance_green: 1.0
bottom_gige_whitebalance_red: 1.0
bottom_gige_width: 1088
bottom_gige_x_offset: 140
bottom_gige_y_offset: 130
bottom_guppy_auto_brightness_auto: true
bottom_guppy_auto_brightness_target: 100
bottom_guppy_auto_brightness_target_variation: 16
bottom_guppy_exposure: 95.0
bottom_guppy_exposure_auto: false
bottom_guppy_format: 0
bottom_guppy_framerate: 0
bottom_guppy_gain: 1.0
bottom_guppy_gain_auto: false
bottom_guppy_gamma: 0
bottom_guppy_guid: '582164340023517285'
bottom_guppy_height: 0
bottom_guppy_name: bottom_guppy
bottom_guppy_saturation: 0
bottom_guppy_shutter: 32.0
bottom_guppy_shutter_auto: false
bottom_guppy_white_balance_auto: true
bottom_guppy_white_balance_blue: 381.0
bottom_guppy_white_balance_red: 568.0
bottom_guppy_whitebalance_auto: true
bottom_guppy_whitebalance_blue: 276.0
bottom_guppy_whitebalance_red: 511.0
bottom_guppy_width: 0
bottom_guppy_x_offset: 0
bottom_guppy_y_offset: 0
default_exposure: 0
default_framerate: 0
default_gain: 350.0
default_gain_auto: true
default_gamma: 0
default_name: default_camera
default_shutter: 500.0
default_shutter_auto: true
default_white_balance_auto: true
default_white_balance_blue: 412.0
default_white_balance_red: 511.0
front_guppy_auto_brightness_auto: true
front_guppy_auto_brightness_target: 100
front_guppy_auto_brightness_target_variation: 16
front_guppy_exposure: 50.0
front_guppy_exposure_auto: false
front_guppy_format: 0
front_guppy_framerate: 0
front_guppy_gain: 1.0
front_guppy_gain_auto: false
front_guppy_gamma: 0
front_guppy_guid: '2892819690326160'
front_guppy_height: 150
front_guppy_name: front_guppy
front_guppy_saturation: 0
front_guppy_shutter: 32.0
front_guppy_shutter_auto: false
front_guppy_white_balance_auto: true
front_guppy_white_balance_blue: 568.0
front_guppy_white_balance_red: 276.0
front_guppy_whitebalance_auto: true
front_guppy_whitebalance_blue: 276.0
front_guppy_whitebalance_red: 568.0
front_guppy_width: 150
front_guppy_x_offset: 0
front_guppy_y_offset: 0
