# File containing all the initial camera parameters for the /provider_vision/default camera.

# Parameters for the /provider_vision/front Guppy Camera
/provider_vision//provider_vision/front_guppy_name: "front_guppy"
/provider_vision/front_guppy_guid: "2892819690326160"
/provider_vision/front_guppy_framerate: 0
/provider_vision/front_guppy_gain_auto: false
/provider_vision/front_guppy_shutter_auto: false
/provider_vision/front_guppy_white_balance_auto: true
/provider_vision/front_guppy_exposure_auto: false
/provider_vision/front_guppy_gain: 1.0
/provider_vision/front_guppy_shutter: 32.0
/provider_vision/front_guppy_gamma: 0
/provider_vision/front_guppy_exposure: 50
/provider_vision/front_guppy_saturation: 0
/provider_vision/front_guppy_white_balance_red: 276.0
/provider_vision/front_guppy_white_balance_blue: 568.0
/provider_vision/front_guppy_width: 0
/provider_vision/front_guppy_height: 0
/provider_vision/front_guppy_x_offset: 0
/provider_vision/front_guppy_y_offset: 0
/provider_vision/front_guppy_format: 0
/provider_vision/front_guppy_auto_brightness_auto: true
/provider_vision/front_guppy_auto_brightness_target: 100
/provider_vision/front_guppy_auto_brightness_target_variation: 16

# Parameters for the /provider_vision/bottom Guppy Camera
/provider_vision/bottom_guppy_name: "bottom_guppy"
/provider_vision/bottom_guppy_guid: "582164340023517285"
/provider_vision/bottom_guppy_framerate: 0
/provider_vision/bottom_guppy_gain_auto: false
/provider_vision/bottom_guppy_shutter_auto: false
/provider_vision/bottom_guppy_white_balance_auto: true
/provider_vision/bottom_guppy_gain: 1.0
/provider_vision/bottom_guppy_shutter: 32.0
/provider_vision/bottom_guppy_gamma: 0
/provider_vision/bottom_guppy_exposure: 95
/provider_vision/bottom_guppy_exposure_auto: false
/provider_vision/bottom_guppy_saturation: 0
/provider_vision/bottom_guppy_white_balance_red: 568.0
/provider_vision/bottom_guppy_white_balance_blue: 381.0
/provider_vision/bottom_guppy_width: 0
/provider_vision/bottom_guppy_height: 0
/provider_vision/bottom_guppy_x_offset: 0
/provider_vision/bottom_guppy_y_offset: 0
/provider_vision/bottom_guppy_format: 0
/provider_vision/bottom_guppy_auto_brightness_auto: true
/provider_vision/bottom_guppy_auto_brightness_target: 100
/provider_vision/bottom_guppy_auto_brightness_target_variation: 16


# Parameters for the /provider_vision/bottom GigE Camera
/provider_vision/bottom_gige_name: "bottom_gige"
/provider_vision/bottom_gige_guid: "1230819763"
/provider_vision/bottom_gige_framerate: 15
/provider_vision/bottom_gige_auto_brightness_auto: false
/provider_vision/bottom_gige_shutter_auto: false
/provider_vision/bottom_gige_shutter: 32.0
/provider_vision/bottom_gige_gamma: 0
/provider_vision/bottom_gige_auto_brightness_target: 100
/provider_vision/bottom_gige_auto_brightness_target_variation: 16
/provider_vision/bottom_gige_gain_auto: false
/provider_vision/bottom_gige_gain: 1
/provider_vision/bottom_gige_saturation: 0
/provider_vision/bottom_gige_exposure: 1000
/provider_vision/bottom_gige_exposure_auto: false
/provider_vision/bottom_gige_white_balance_auto: true
/provider_vision/bottom_gige_white_balance_red: 568.0
/provider_vision/bottom_gige_white_balance_blue: 381.0
/provider_vision/bottom_gige_width: 1088
/provider_vision/bottom_gige_height: 780
/provider_vision/bottom_gige_x_offset: 140
/provider_vision/bottom_gige_y_offset: 130
/provider_vision/bottom_gige_format: 17301513

# Parameters for the all other camera (/provider_vision/default configurations)
/provider_vision/default_name: "default_camera"
/provider_vision/default_framerate: 0
/provider_vision/default_gain_auto: true
/provider_vision/default_shutter_auto: true
/provider_vision/default_white_balance_auto: true
/provider_vision/default_gain: 350.0
/provider_vision/default_shutter: 500.0
/provider_vision/default_gamma: 0
/provider_vision/default_exposure: 0
/provider_vision/default_white_balance_red: 511.0
/provider_vision/default_white_balance_blue: 412.0
