# Parameters for the Front Guppy Camera
/provider_vision/camera_pid/front_guppy/calibration_activated: true

/provider_vision/camera_pid/front_guppy/gamma_i_gain: 1
/provider_vision/camera_pid/front_guppy/gamma_p_gain: 0.5
/provider_vision/camera_pid/front_guppy/gamma_d_gain: 0.75

/provider_vision/camera_pid/front_guppy/gain_i_gain: 1
/provider_vision/camera_pid/front_guppy/gain_p_gain: 0.5
/provider_vision/camera_pid/front_guppy/gain_d_gain: 0.75

/provider_vision/camera_pid/front_guppy/exposure_i_gain: 1
/provider_vision/camera_pid/front_guppy/exposure_p_gain: 0.5
/provider_vision/camera_pid/front_guppy/exposure_d_gain: 0.75

/provider_vision/camera_pid/front_guppy/saturation_i_gain: 1
/provider_vision/camera_pid/front_guppy/saturation_p_gain: 0.5
/provider_vision/camera_pid/front_guppy/saturation_d_gain: 0.75

/provider_vision/camera_pid/front_guppy/gain_lim: 600.0
/provider_vision/camera_pid/front_guppy/exposure_lim: 190.0

# Parameters for the Bottom Guppy Camera
/provider_vision/camera_pid/bottom_guppy/calibration_activated: false

/provider_vision/camera_pid/bottom_guppy/gamma_i_gain: 1
/provider_vision/camera_pid/bottom_guppy/gamma_p_gain: 0.5
/provider_vision/camera_pid/bottom_guppy/gamma_d_gain: 0.75

/provider_vision/camera_pid/bottom_guppy/gain_i_gain: 1
/provider_vision/camera_pid/bottom_guppy/gain_p_gain: 0.5
/provider_vision/camera_pid/bottom_guppy/gain_d_gain: 0.75

/provider_vision/camera_pid/bottom_guppy/exposure_i_gain: 1
/provider_vision/camera_pid/bottom_guppy/exposure_p_gain: 0.5
/provider_vision/camera_pid/bottom_guppy/exposure_d_gain: 0.75

/provider_vision/camera_pid/bottom_guppy/saturation_i_gain: 1
/provider_vision/camera_pid/bottom_guppy/saturation_p_gain: 0.5
/provider_vision/camera_pid/bottom_guppy/saturation_d_gain: 0.75

/provider_vision/camera_pid/bottom_guppy/gain_lim: 480.0
/provider_vision/camera_pid/bottom_guppy/exposure_lim: 80.0
