name: object_feature_output
filters:
  - name: Rotate
    id: 0
    parameters:
      - type: Boolean
        name: enable
        value: 0
      - value: 0
        type: Integer
        name: Rotation_type
  - id: 1
    parameters:
      - type: Boolean
        name: enable
        value: 0
      - type: Integer
        name: Rotation_type
        value: 0
    name: Rotate
  - name: SubtractAllPlanes
    id: 2
    parameters:
      - type: Boolean
        name: enable
        value: 0
      - value: 1
        name: Plane_1
        type: Integer
      - type: Integer
        value: 1
        name: Plane_2
      - value: 1
        name: Plane_3
        type: Integer
      - value: 0
        name: Invert_plane_1
        type: Boolean
      - type: Boolean
        name: Invert_plane_2
        value: 0
      - value: 0
        type: Boolean
        name: Invert_plane_3
      - value: 1.000000
        type: Double
        name: Weight_Plane_1
      - name: Weight_Plane_2
        type: Double
        value: 1.000000
      - type: Double
        value: 1.000000
        name: Weight_Plane_3
  - name: Blurr
    id: 3
    parameters:
      - value: 0
        name: Enable
        type: Boolean
      - name: Type
        type: Integer
        value: 2
      - type: Integer
        value: 1
        name: Kernel_size
  - name: StatsThreshold
    id: 4
    parameters:
      - type: Boolean
        value: 0
        name: Enable
      - type: Integer
        value: 0
        name: Min_thresh
      - type: Double
        value: 1.000000
        name: Mean_multiplier
      - type: Double
        name: Standard_deviation_multiplier
        value: 1.000000
  - id: 5
    name: Threshold
    parameters:
      - type: Boolean
        value: 0
        name: Enable
      - name: Threshold_type
        value: 1
        type: Integer
      - value: 100
        name: Max_value
        type: Integer
  - name: Erode
    id: 6
    parameters:
      - name: Enable
        type: Boolean
        value: 0
      - name: Square_kernel
        value: 1
        type: Boolean
      - value: 0
        type: Integer
        name: Kernel_type
      - type: Integer
        value: 1
        name: Width
      - name: Height
        value: 1
        type: Integer
      - name: Iteration
        value: 1
        type: Integer
  - name: Dilate
    id: 7
    parameters:
      - value: 0
        name: Enable
        type: Boolean
      - type: Boolean
        name: Square_kernel
        value: 1
      - type: Integer
        name: Kernel_type
        value: 0
      - name: Width
        type: Integer
        value: 1
      - name: Height
        type: Integer
        value: 1
      - name: Iteration
        type: Integer
        value: 1
  - id: 8
    name: ObjectFeatureCalculator
    parameters:
      - type: Boolean
        value: 0
        name: Enable
      - value: 0
        name: Debug_contour
        type: Boolean
      - type: Boolean
        value: 0
        name: toggle_recording
      - value: buoy
        name: ID
        type: String
      - name: spec1
        type: String
        value: red
      - name: spec2
        value: blue
        type: String
      - type: String
        name: output_folder
        value: /home/jeremie/aidata/rec1/
      - name: Min_area
        type: Double
        value: 200.000000