filters:
  - name: ImageAccumulator
    parameters:
      - value: 0
        type: Boolean
        name: Enable
      - type: Integer
        name: NB_of_images
        value: 3
      - type: Integer
        value: 1
        name: Method_to_use
    id: 0
  - name: SubtractAllPlanes
    parameters:
      - name: enable
        value: 0
        type: Boolean
      - name: Plane_1
        type: Integer
        value: 1
      - name: Plane_2
        value: 1
        type: Integer
      - name: Plane_3
        type: Integer
        value: 1
      - type: Boolean
        value: 0
        name: Invert_plane_1
      - value: 0
        name: Invert_plane_2
        type: Boolean
      - type: Boolean
        value: 0
        name: Invert_plane_3
      - type: Double
        value: 1.000000
        name: Weight_Plane_1
      - type: Double
        value: 1.000000
        name: Weight_Plane_2
      - value: 1.000000
        name: Weight_Plane_3
        type: Double
    id: 1
  - id: 2
    name: Blurr
    parameters:
      - value: 0
        name: Enable
        type: Boolean
      - type: Integer
        name: Type
        value: 2
      - type: Integer
        name: Kernel_size
        value: 1
  - name: Sobel
    id: 3
    parameters:
      - name: Enable
        type: Boolean
        value: 0
      - value: 1
        type: Boolean
        name: Convert_to_uchar
      - value: 0
        name: use_pixel_intensity_correction
        type: Boolean
      - type: Double
        value: 0.000000
        name: Delta
      - type: Double
        name: Scale
        value: 1.000000
      - type: Double
        name: pixel_correction_power
        value: 1.000000
      - name: Size
        type: Integer
        value: 2
  - parameters:
      - name: Enable
        value: 0
        type: Boolean
      - type: Integer
        value: 0
        name: Morphology_type
      - name: Kernel_type
        type: Integer
        value: 0
      - type: Integer
        value: 1
        name: Iteration
      - value: 1
        type: Integer
        name: Kernel_size
    name: Morphology
    id: 4
  - name: StatsThreshold
    id: 5
    parameters:
      - name: Enable
        type: Boolean
        value: 0
      - value: 0
        name: Min_thresh
        type: Integer
      - name: Mean_multiplier
        type: Double
        value: 1.000000
      - name: Standard_deviation_multiplier
        value: 1.000000
        type: Double
  - name: Threshold
    id: 6
    parameters:
      - value: 0
        type: Boolean
        name: Enable
      - name: Threshold_type
        value: 1
        type: Integer
      - value: 100
        type: Integer
        name: Max_value
  - name: Erode
    parameters:
      - type: Boolean
        name: Enable
        value: 0
      - name: Square_kernel
        type: Boolean
        value: 1
      - name: Kernel_type
        value: 0
        type: Integer
      - name: Width
        type: Integer
        value: 1
      - value: 1
        name: Height
        type: Integer
      - name: Iteration
        type: Integer
        value: 1
    id: 7
  - name: Dilate
    parameters:
      - type: Boolean
        name: Enable
        value: 0
      - value: 1
        name: Square_kernel
        type: Boolean
      - value: 0
        type: Integer
        name: Kernel_type
      - value: 1
        name: Width
        type: Integer
      - type: Integer
        value: 1
        name: Height
      - name: Iteration
        value: 1
        type: Integer
    id: 8
  - name: FenceDetector
    id: 9
    parameters:
      - name: Enable
        value: 0
        type: Boolean
      - value: 0
        type: Boolean
        name: Debug_contour
      - value: 0
        name: Search_only_bottom
        type: Boolean
      - value: 50
        type: Integer
        name: Minimum_length
      - value: 50
        name: Max_dist_from_extremum
        type: Integer
      - value: 300
        name: Minimum_area
        type: Integer
      - name: Max_diff_horizontal
        value: 20
        type: Integer
      - value: 20
        type: Integer
        name: Max_diff_vertical
      - type: Integer
        name: Minimum_percent_filled
        value: 70
name: simple_fence_big