filters:
  - id: 0
    name: Rotate
    parameters:
      - value: 0
        type: Boolean
        name: enable
      - name: Rotation_type
        value: 0
        type: Integer
  - id: 1
    parameters:
      - type: Boolean
        name: enable
        value: 0
      - name: Rotation_type
        type: Integer
        value: 0
    name: Rotate
  - id: 2
    name: SubtractAllPlanes
    parameters:
      - value: 0
        name: enable
        type: Boolean
      - type: Integer
        value: 1
        name: Plane_1
      - value: 1
        name: Plane_2
        type: Integer
      - value: 1
        name: Plane_3
        type: Integer
      - value: 0
        name: Invert_plane_1
        type: Boolean
      - type: Boolean
        name: Invert_plane_2
        value: 0
      - type: Boolean
        name: Invert_plane_3
        value: 0
      - type: Double
        value: 1.000000
        name: Weight_Plane_1
      - value: 1.000000
        type: Double
        name: Weight_Plane_2
      - name: Weight_Plane_3
        type: Double
        value: 1.000000
  - name: Blurr
    parameters:
      - type: Boolean
        name: Enable
        value: 0
      - type: Integer
        value: 2
        name: Type
      - value: 1
        name: Kernel_size
        type: Integer
    id: 3
  - name: StatsThreshold
    parameters:
      - name: Enable
        value: 0
        type: Boolean
      - value: 0
        name: Min_thresh
        type: Integer
      - type: Double
        value: 1.000000
        name: Mean_multiplier
      - name: Standard_deviation_multiplier
        type: Double
        value: 1.000000
    id: 4
  - id: 5
    parameters:
      - value: 0
        name: Enable
        type: Boolean
      - value: 1
        name: Threshold_type
        type: Integer
      - value: 100
        name: Max_value
        type: Integer
    name: Threshold
  - parameters:
      - name: Enable
        value: 0
        type: Boolean
      - type: Boolean
        name: Square_kernel
        value: 1
      - type: Integer
        name: Kernel_type
        value: 0
      - value: 1
        name: Width
        type: Integer
      - type: Integer
        name: Height
        value: 1
      - type: Integer
        name: Iteration
        value: 1
    id: 6
    name: Erode
  - id: 7
    parameters:
      - type: Boolean
        value: 0
        name: Enable
      - name: Square_kernel
        value: 1
        type: Boolean
      - value: 0
        name: Kernel_type
        type: Integer
      - value: 1
        name: Width
        type: Integer
      - type: Integer
        name: Height
        value: 1
      - name: Iteration
        value: 1
        type: Integer
    name: Dilate
  - parameters:
      - value: 0
        type: Boolean
        name: Enable
      - value: 0
        name: Debug_contour
        type: Boolean
      - name: Look_for_Rectangle
        value: 0
        type: Boolean
      - type: Double
        name: Min_area
        value: 200.000000
    id: 8
    name: PipeDetector
name: simple_pipe