filters:
  - id: 0
    parameters:
      - type: Boolean
        value: 0
        name: enable
      - name: Rotation_type
        type: Integer
        value: 0
    name: Rotate
  - id: 1
    parameters:
      - name: Enable
        type: Boolean
        value: 0
      - type: Boolean
        name: Square_kernel
        value: 1
      - type: Integer
        name: Kernel_type
        value: 0
      - type: Integer
        name: Width
        value: 1
      - type: Integer
        value: 1
        name: Height
      - name: Iteration
        type: Integer
        value: 1
    name: Dilate
  - id: 2
    parameters:
      - name: enable
        value: 0
        type: Boolean
      - value: 1
        type: Integer
        name: Plane_1
      - value: 1
        type: Integer
        name: Plane_2
      - type: Integer
        name: Plane_3
        value: 1
      - type: Boolean
        value: 0
        name: Invert_plane_1
      - type: Boolean
        value: 0
        name: Invert_plane_2
      - type: Boolean
        name: Invert_plane_3
        value: 0
      - name: Weight_Plane_1
        value: 1.000000
        type: Double
      - name: Weight_Plane_2
        value: 1.000000
        type: Double
      - value: 1.000000
        type: Double
        name: Weight_Plane_3
    name: SubtractAllPlanes
  - parameters:
      - value: 0
        name: Enable
        type: Boolean
      - type: Integer
        value: 2
        name: Type
      - name: Kernel_size
        type: Integer
        value: 1
    id: 3
    name: Blurr
  - parameters:
      - type: Boolean
        name: Enable
        value: 0
      - type: Boolean
        value: 1
        name: Convert_to_uchar
      - value: 0
        type: Boolean
        name: use_pixel_intensity_correction
      - type: Double
        name: Delta
        value: 0.000000
      - type: Double
        name: Scale
        value: 1.000000
      - name: pixel_correction_power
        value: 1.000000
        type: Double
      - name: Size
        type: Integer
        value: 2
    name: Sobel
    id: 4
  - parameters:
      - value: 0
        type: Boolean
        name: Enable
      - value: 0
        name: Min_thresh
        type: Integer
      - value: 1.000000
        type: Double
        name: Mean_multiplier
      - type: Double
        name: Standard_deviation_multiplier
        value: 1.000000
    id: 5
    name: StatsThreshold
  - id: 6
    parameters:
      - type: Boolean
        value: 0
        name: Enable
      - name: Threshold_type
        value: 1
        type: Integer
      - value: 100
        name: Max_value
        type: Integer
    name: Threshold
  - name: Erode
    id: 7
    parameters:
      - name: Enable
        type: Boolean
        value: 0
      - type: Boolean
        value: 1
        name: Square_kernel
      - type: Integer
        name: Kernel_type
        value: 0
      - value: 1
        name: Width
        type: Integer
      - name: Height
        type: Integer
        value: 1
      - type: Integer
        value: 1
        name: Iteration
  - parameters:
      - name: Enable
        type: Boolean
        value: 0
      - name: Square_kernel
        value: 1
        type: Boolean
      - value: 0
        type: Integer
        name: Kernel_type
      - type: Integer
        value: 1
        name: Width
      - type: Integer
        value: 1
        name: Height
      - type: Integer
        value: 1
        name: Iteration
    name: Dilate
    id: 8
  - name: DeloreanDetector
    parameters:
      - name: Enable
        type: Boolean
        value: 0
      - type: Boolean
        name: Debug_contour
        value: 0
      - value: 0
        name: Output_train
        type: Boolean
      - type: Double
        name: Min_area
        value: 200.000000
      - type: Double
        value: 0.500000
        name: Ratio_target_big
      - name: Ratio_target_small
        type: Double
        value: 0.500000
      - type: Double
        value: 0.100000
        name: Diff_from_ratio_target
    id: 9
name: simple_delorean_near