filters:
  - id: 0
    name: Rotate
    parameters:
      - type: Boolean
        value: 0
        name: enable
      - name: Rotation_type
        type: Integer
        value: 0
  - name: Dilate
    parameters:
      - type: Boolean
        value: 0
        name: Enable
      - value: 1
        name: Square_kernel
        type: Boolean
      - type: Integer
        value: 0
        name: Kernel_type
      - type: Integer
        name: Width
        value: 1
      - type: Integer
        name: Height
        value: 1
      - value: 1
        type: Integer
        name: Iteration
    id: 1
  - id: 2
    parameters:
      - name: Enable
        type: Boolean
        value: 0
      - type: Integer
        name: Morphology_type
        value: 0
      - type: Integer
        value: 0
        name: Kernel_type
      - type: Integer
        name: Iteration
        value: 1
      - value: 1
        type: Integer
        name: Kernel_size
    name: Morphology
  - parameters:
      - value: 0
        name: enable
        type: Boolean
      - value: 1
        type: Integer
        name: Plane_1
      - type: Integer
        name: Plane_2
        value: 1
      - name: Plane_3
        value: 1
        type: Integer
      - type: Boolean
        name: Invert_plane_1
        value: 0
      - name: Invert_plane_2
        type: Boolean
        value: 0
      - value: 0
        name: Invert_plane_3
        type: Boolean
      - name: Weight_Plane_1
        value: 1.000000
        type: Double
      - value: 1.000000
        type: Double
        name: Weight_Plane_2
      - type: Double
        name: Weight_Plane_3
        value: 1.000000
    name: SubtractAllPlanes
    id: 3
  - parameters:
      - name: Enable
        value: 0
        type: Boolean
      - name: Type
        value: 2
        type: Integer
      - value: 1
        name: Kernel_size
        type: Integer
    id: 4
    name: Blurr
  - name: Sobel
    parameters:
      - type: Boolean
        name: Enable
        value: 0
      - type: Boolean
        value: 1
        name: Convert_to_uchar
      - name: use_pixel_intensity_correction
        type: Boolean
        value: 0
      - value: 0.000000
        type: Double
        name: Delta
      - type: Double
        value: 1.000000
        name: Scale
      - type: Double
        value: 1.000000
        name: pixel_correction_power
      - name: Size
        type: Integer
        value: 2
    id: 5
  - id: 6
    name: ScharrAdding
    parameters:
      - value: 0
        type: Boolean
        name: Enable
      - type: Boolean
        value: 1
        name: Run_small_image
      - type: Boolean
        name: Convert_to_uchar
        value: 0
      - name: Delta
        value: 0.000000
        type: Double
      - value: 1.000000
        type: Double
        name: Scale
      - type: Double
        value: 1.000000
        name: Mean_multiplier
      - value: 0
        name: Blue
        type: Boolean
      - value: 0
        type: Boolean
        name: Green
      - name: Red
        value: 0
        type: Boolean
      - name: Hue
        value: 0
        type: Boolean
      - value: 0
        name: Saturation
        type: Boolean
      - name: Intensity
        value: 0
        type: Boolean
      - value: 0
        type: Boolean
        name: Gray
  - id: 7
    parameters:
      - value: 0
        type: Boolean
        name: Enable
      - name: Morphology_type
        value: 0
        type: Integer
      - value: 0
        name: Kernel_type
        type: Integer
      - type: Integer
        value: 1
        name: Iteration
      - name: Kernel_size
        value: 1
        type: Integer
    name: Morphology
  - name: StatsThreshold
    parameters:
      - value: 0
        type: Boolean
        name: Enable
      - type: Integer
        name: Min_thresh
        value: 0
      - value: 1.000000
        type: Double
        name: Mean_multiplier
      - type: Double
        value: 1.000000
        name: Standard_deviation_multiplier
    id: 8
  - name: Threshold
    parameters:
      - type: Boolean
        name: Enable
        value: 0
      - name: Threshold_type
        type: Integer
        value: 1
      - name: Max_value
        value: 100
        type: Integer
    id: 9
  - name: Erode
    parameters:
      - name: Enable
        type: Boolean
        value: 0
      - name: Square_kernel
        type: Boolean
        value: 1
      - type: Integer
        value: 0
        name: Kernel_type
      - value: 1
        type: Integer
        name: Width
      - type: Integer
        value: 1
        name: Height
      - type: Integer
        name: Iteration
        value: 1
    id: 10
  - parameters:
      - type: Boolean
        name: Enable
        value: 0
      - value: 1
        type: Boolean
        name: Square_kernel
      - type: Integer
        name: Kernel_type
        value: 0
      - name: Width
        value: 1
        type: Integer
      - type: Integer
        value: 1
        name: Height
      - name: Iteration
        value: 1
        type: Integer
    id: 11
    name: Dilate
  - name: SubmarineFrameMasker
    id: 12
    parameters:
      - value: 0
        type: Boolean
        name: Enable
      - name: Rotation_type
        value: 0
        type: Integer
  - parameters:
      - value: 0
        type: Boolean
        name: Enable
      - type: Boolean
        value: 0
        name: Debug_contour
      - name: Output_train
        value: 0
        type: Boolean
      - type: Double
        name: Min_area
        value: 200.000000
      - type: Double
        name: Ratio_target_big
        value: 0.500000
      - type: Double
        value: 0.500000
        name: Ratio_target_small
      - name: Diff_from_ratio_target
        value: 0.100000
        type: Double
    id: 13
    name: DeloreanDetector
name: simple_delorean_far