name: simple_buoy_green
filters:
  - id: 0
    parameters:
      - value: 0
        name: Enable
        type: Boolean
      - name: NB_of_images
        type: Integer
        value: 3
      - name: Method_to_use
        type: Integer
        value: 1
    name: ImageAccumulator
  - id: 1
    name: InRange
    parameters:
      - type: Boolean
        name: Enable
        value: 0
      - value: 0
        type: Integer
        name: HSVLowH
      - type: Integer
        name: HSVHighH
        value: 255
      - value: 0
        name: HSVLowS
        type: Integer
      - type: Integer
        name: HSVHighS
        value: 255
      - name: HSVLowV
        value: 0
        type: Integer
      - value: 255
        name: HSVHighV
        type: Integer
      - value: 0
        name: LUVlowL
        type: Integer
      - name: LUVhighL
        value: 255
        type: Integer
      - name: LUVlowU
        value: 0
        type: Integer
      - type: Integer
        name: LUVhighU
        value: 255
      - type: Integer
        name: LUVlowV
        value: 0
      - value: 255
        type: Integer
        name: LUVhighV
  - name: SubtractAllPlanes
    id: 2
    parameters:
      - name: enable
        type: Boolean
        value: 0
      - name: Plane_1
        type: Integer
        value: 1
      - type: Integer
        value: 1
        name: Plane_2
      - type: Integer
        value: 1
        name: Plane_3
      - type: Boolean
        name: Invert_plane_1
        value: 0
      - type: Boolean
        value: 0
        name: Invert_plane_2
      - value: 0
        type: Boolean
        name: Invert_plane_3
      - name: Weight_Plane_1
        type: Double
        value: 1.000000
      - value: 1.000000
        type: Double
        name: Weight_Plane_2
      - name: Weight_Plane_3
        value: 1.000000
        type: Double
  - name: WhiteNoiseTakedown
    id: 3
    parameters:
      - value: 0
        name: Enable
        type: Boolean
      - name: LowB
        type: Integer
        value: 0
      - type: Integer
        value: 0
        name: HighB
      - type: Integer
        value: 0
        name: LowG
      - name: HighG
        value: 0
        type: Integer
      - type: Integer
        name: LowR
        value: 0
      - type: Integer
        value: 0
        name: HighR
      - type: Integer
        value: 0
        name: Channel_view
  - parameters:
      - name: Enable
        value: 0
        type: Boolean
      - value: 2
        type: Integer
        name: Type
      - value: 1
        type: Integer
        name: Kernel_size
    name: Blurr
    id: 4
  - id: 5
    name: StatsThreshold
    parameters:
      - name: Enable
        type: Boolean
        value: 0
      - value: 0
        name: Min_thresh
        type: Integer
      - name: Mean_multiplier
        type: Double
        value: 1.000000
      - type: Double
        name: Standard_deviation_multiplier
        value: 1.000000
  - id: 6
    name: Threshold
    parameters:
      - value: 0
        name: Enable
        type: Boolean
      - name: Threshold_type
        type: Integer
        value: 1
      - name: Max_value
        value: 100
        type: Integer
  - name: Dilate
    parameters:
      - type: Boolean
        name: Enable
        value: 0
      - type: Boolean
        name: Square_kernel
        value: 1
      - value: 0
        type: Integer
        name: Kernel_type
      - name: Width
        type: Integer
        value: 1
      - type: Integer
        value: 1
        name: Height
      - value: 1
        type: Integer
        name: Iteration
    id: 7
  - parameters:
      - name: Enable
        type: Boolean
        value: 0
      - name: Square_kernel
        type: Boolean
        value: 1
      - value: 0
        name: Kernel_type
        type: Integer
      - name: Width
        value: 1
        type: Integer
      - name: Height
        value: 1
        type: Integer
      - value: 1
        name: Iteration
        type: Integer
    name: Erode
    id: 8
  - parameters:
      - value: 0
        name: Enable
        type: Boolean
      - type: Boolean
        name: Debug_contour
        value: 0
      - name: Eliminate_same_x
        type: Boolean
        value: 0
      - name: Detect_red
        type: Boolean
        value: 0
      - name: Buoy
        value: red
        type: String
      - type: Double
        value: 200.000000
        name: Min_area
      - value: 50.000000
        type: Double
        name: Max_ratio
      - name: Min_percent
        type: Double
        value: 50.000000
      - type: Double
        name: Min_x_difference
        value: 50.000000
      - value: 50.000000
        type: Double
        name: Ratio_for_angle_check
      - type: Double
        value: 50.000000
        name: horizontal_max_angle
    name: BuoySingle
    id: 9