filters:
  - parameters:
      - type: Boolean
        name: enable
        value: 0
      - type: Integer
        value: 0
        name: Rotation_type
    id: 0
    name: Rotate
  - name: Dilate
    id: 1
    parameters:
      - type: Boolean
        name: Enable
        value: 0
      - value: 1
        type: Boolean
        name: Square_kernel
      - name: Kernel_type
        type: Integer
        value: 0
      - value: 1
        type: Integer
        name: Width
      - value: 1
        type: Integer
        name: Height
      - value: 1
        type: Integer
        name: Iteration
  - name: Morphology
    parameters:
      - type: Boolean
        name: Enable
        value: 0
      - type: Integer
        value: 0
        name: Morphology_type
      - value: 0
        type: Integer
        name: Kernel_type
      - value: 1
        type: Integer
        name: Iteration
      - name: Kernel_size
        type: Integer
        value: 1
    id: 2
  - parameters:
      - type: Boolean
        value: 0
        name: enable
      - name: Plane_1
        value: 1
        type: Integer
      - type: Integer
        name: Plane_2
        value: 1
      - value: 1
        name: Plane_3
        type: Integer
      - name: Invert_plane_1
        value: 0
        type: Boolean
      - name: Invert_plane_2
        type: Boolean
        value: 0
      - name: Invert_plane_3
        type: Boolean
        value: 0
      - name: Weight_Plane_1
        value: 1.000000
        type: Double
      - name: Weight_Plane_2
        type: Double
        value: 1.000000
      - name: Weight_Plane_3
        value: 1.000000
        type: Double
    id: 3
    name: SubtractAllPlanes
  - parameters:
      - value: 0
        name: Enable
        type: Boolean
      - value: 2
        type: Integer
        name: Type
      - name: Kernel_size
        type: Integer
        value: 1
    name: Blurr
    id: 4
  - name: Sobel
    parameters:
      - value: 0
        name: Enable
        type: Boolean
      - value: 1
        name: Convert_to_uchar
        type: Boolean
      - value: 0
        type: Boolean
        name: use_pixel_intensity_correction
      - name: Delta
        type: Double
        value: 0.000000
      - type: Double
        value: 1.000000
        name: Scale
      - value: 1.000000
        type: Double
        name: pixel_correction_power
      - value: 2
        name: Size
        type: Integer
    id: 5
  - id: 6
    name: ScharrAdding
    parameters:
      - type: Boolean
        value: 0
        name: Enable
      - value: 1
        name: Run_small_image
        type: Boolean
      - name: Convert_to_uchar
        value: 0
        type: Boolean
      - type: Double
        value: 0.000000
        name: Delta
      - name: Scale
        value: 1.000000
        type: Double
      - name: Mean_multiplier
        value: 1.000000
        type: Double
      - name: Blue
        type: Boolean
        value: 0
      - value: 0
        name: Green
        type: Boolean
      - value: 0
        name: Red
        type: Boolean
      - type: Boolean
        name: Hue
        value: 0
      - name: Saturation
        value: 0
        type: Boolean
      - type: Boolean
        value: 0
        name: Intensity
      - type: Boolean
        value: 0
        name: Gray
  - id: 7
    parameters:
      - value: 0
        type: Boolean
        name: Enable
      - type: Integer
        value: 0
        name: Morphology_type
      - value: 0
        type: Integer
        name: Kernel_type
      - name: Iteration
        type: Integer
        value: 1
      - value: 1
        name: Kernel_size
        type: Integer
    name: Morphology
  - parameters:
      - type: Boolean
        name: Enable
        value: 0
      - value: 0
        type: Integer
        name: Min_thresh
      - name: Mean_multiplier
        value: 1.000000
        type: Double
      - type: Double
        name: Standard_deviation_multiplier
        value: 1.000000
    id: 8
    name: StatsThreshold
  - id: 9
    parameters:
      - name: Enable
        type: Boolean
        value: 0
      - type: Integer
        name: Threshold_type
        value: 1
      - value: 100
        name: Max_value
        type: Integer
    name: Threshold
  - parameters:
      - value: 0
        type: Boolean
        name: Enable
      - type: Boolean
        name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
        type: Integer
      - type: Integer
        name: Width
        value: 1
      - name: Height
        type: Integer
        value: 1
      - value: 1
        type: Integer
        name: Iteration
    name: Erode
    id: 10
  - id: 11
    name: Dilate
    parameters:
      - name: Enable
        type: Boolean
        value: 0
      - name: Square_kernel
        value: 1
        type: Boolean
      - value: 0
        name: Kernel_type
        type: Integer
      - value: 1
        name: Width
        type: Integer
      - name: Height
        type: Integer
        value: 1
      - name: Iteration
        value: 1
        type: Integer
  - id: 12
    name: SubmarineFrameMasker
    parameters:
      - name: Enable
        value: 0
        type: Boolean
      - value: 0
        type: Integer
        name: Rotation_type
  - name: DeloreanDetector
    id: 13
    parameters:
      - type: Boolean
        value: 0
        name: Enable
      - name: Debug_contour
        value: 0
        type: Boolean
      - name: Output_train
        value: 0
        type: Boolean
      - value: 200.000000
        name: Min_area
        type: Double
      - name: Ratio_target_big
        value: 0.500000
        type: Double
      - type: Double
        name: Ratio_target_small
        value: 0.500000
      - name: Diff_from_ratio_target
        value: 0.100000
        type: Double
name: simple_delorean_near_bache