filters:
  - parameters:
      - value: 0
        type: Boolean
        name: enable
      - value: 0
        type: Integer
        name: Rotation_type
    id: 0
    name: Rotate
  - id: 1
    parameters:
      - value: 0
        name: Enable
        type: Boolean
      - value: 1
        name: Square_kernel
        type: Boolean
      - type: Integer
        name: Kernel_type
        value: 0
      - value: 1
        type: Integer
        name: Width
      - type: Integer
        value: 1
        name: Height
      - type: Integer
        value: 1
        name: Iteration
    name: Dilate
  - parameters:
      - value: 0
        type: Boolean
        name: enable
      - name: Plane_1
        type: Integer
        value: 1
      - value: 1
        type: Integer
        name: Plane_2
      - name: Plane_3
        value: 1
        type: Integer
      - value: 0
        name: Invert_plane_1
        type: Boolean
      - name: Invert_plane_2
        type: Boolean
        value: 0
      - value: 0
        type: Boolean
        name: Invert_plane_3
      - value: 1.000000
        name: Weight_Plane_1
        type: Double
      - value: 1.000000
        type: Double
        name: Weight_Plane_2
      - name: Weight_Plane_3
        value: 1.000000
        type: Double
    name: SubtractAllPlanes
    id: 2
  - id: 3
    parameters:
      - value: 0
        type: Boolean
        name: Enable
      - name: Type
        value: 2
        type: Integer
      - type: Integer
        name: Kernel_size
        value: 1
    name: Blurr
  - id: 4
    name: Sobel
    parameters:
      - name: Enable
        value: 0
        type: Boolean
      - type: Boolean
        value: 1
        name: Convert_to_uchar
      - name: use_pixel_intensity_correction
        value: 0
        type: Boolean
      - value: 0.000000
        name: Delta
        type: Double
      - type: Double
        name: Scale
        value: 1.000000
      - name: pixel_correction_power
        type: Double
        value: 1.000000
      - value: 2
        type: Integer
        name: Size
  - name: StatsThreshold
    parameters:
      - value: 0
        type: Boolean
        name: Enable
      - name: Min_thresh
        value: 0
        type: Integer
      - type: Double
        name: Mean_multiplier
        value: 1.000000
      - type: Double
        name: Standard_deviation_multiplier
        value: 1.000000
    id: 5
  - name: Threshold
    parameters:
      - type: Boolean
        name: Enable
        value: 0
      - name: Threshold_type
        type: Integer
        value: 1
      - type: Integer
        name: Max_value
        value: 100
    id: 6
  - id: 7
    parameters:
      - name: Enable
        value: 0
        type: Boolean
      - type: Boolean
        name: Square_kernel
        value: 1
      - value: 0
        type: Integer
        name: Kernel_type
      - type: Integer
        name: Width
        value: 1
      - type: Integer
        name: Height
        value: 1
      - name: Iteration
        type: Integer
        value: 1
    name: Erode
  - name: Dilate
    id: 8
    parameters:
      - name: Enable
        type: Boolean
        value: 0
      - name: Square_kernel
        type: Boolean
        value: 1
      - type: Integer
        value: 0
        name: Kernel_type
      - type: Integer
        name: Width
        value: 1
      - name: Height
        value: 1
        type: Integer
      - value: 1
        name: Iteration
        type: Integer
  - id: 9
    name: DeloreanDetector
    parameters:
      - type: Boolean
        value: 0
        name: Enable
      - type: Boolean
        value: 0
        name: Debug_contour
      - type: Boolean
        value: 0
        name: Output_train
      - value: 200.000000
        name: Min_area
        type: Double
      - type: Double
        name: Ratio_target_big
        value: 0.500000
      - type: Double
        name: Ratio_target_small
        value: 0.500000
      - value: 0.100000
        type: Double
        name: Diff_from_ratio_target
name: simple_train