name: simple_torpedoes_handle
filters:
  - name: SubtractAllPlanes
    id: 0
    parameters:
      - value: 0
        name: enable
        type: Boolean
      - name: Plane_1
        value: 1
        type: Integer
      - value: 1
        name: Plane_2
        type: Integer
      - name: Plane_3
        type: Integer
        value: 1
      - name: Invert_plane_1
        value: 0
        type: Boolean
      - value: 0
        type: Boolean
        name: Invert_plane_2
      - type: Boolean
        value: 0
        name: Invert_plane_3
      - name: Weight_Plane_1
        value: 1.000000
        type: Double
      - type: Double
        name: Weight_Plane_2
        value: 1.000000
      - type: Double
        name: Weight_Plane_3
        value: 1.000000
  - id: 1
    name: WhiteNoiseTakedown
    parameters:
      - value: 0
        name: Enable
        type: Boolean
      - value: 0
        type: Integer
        name: LowB
      - name: HighB
        value: 0
        type: Integer
      - value: 0
        type: Integer
        name: LowG
      - type: Integer
        name: HighG
        value: 0
      - name: LowR
        value: 0
        type: Integer
      - name: HighR
        type: Integer
        value: 0
      - name: Channel_view
        type: Integer
        value: 0
  - name: Threshold
    id: 2
    parameters:
      - type: Boolean
        value: 0
        name: Enable
      - value: 1
        name: Threshold_type
        type: Integer
      - type: Integer
        value: 100
        name: Max_value
  - name: Morphology
    id: 3
    parameters:
      - type: Boolean
        name: Enable
        value: 0
      - value: 0
        name: Morphology_type
        type: Integer
      - value: 0
        name: Kernel_type
        type: Integer
      - name: Iteration
        value: 1
        type: Integer
      - type: Integer
        value: 1
        name: Kernel_size
  - name: Erode
    id: 4
    parameters:
      - type: Boolean
        name: Enable
        value: 0
      - type: Boolean
        name: Square_kernel
        value: 1
      - name: Kernel_type
        value: 0
        type: Integer
      - name: Width
        type: Integer
        value: 1
      - value: 1
        name: Height
        type: Integer
      - name: Iteration
        value: 1
        type: Integer
  - id: 5
    parameters:
      - name: Enable
        value: 0
        type: Boolean
      - name: Square_kernel
        value: 1
        type: Boolean
      - type: Integer
        value: 0
        name: Kernel_type
      - value: 1
        type: Integer
        name: Width
      - value: 1
        name: Height
        type: Integer
      - name: Iteration
        value: 1
        type: Integer
    name: Dilate
  - parameters:
      - type: Boolean
        value: 0
        name: Enable
      - value: 0
        name: Debug_contour
        type: Boolean
      - value: 0
        name: Look_for_Rectangle
        type: Boolean
      - type: Boolean
        value: 0
        name: disable_ratio_check
      - name: disable_angle_check
        type: Boolean
        value: 0
      - value: 0
        type: Boolean
        name: Use_convex_hull
      - value: 0
        name: Vote_most_centered
        type: Boolean
      - name: Vote_most_upright
        type: Boolean
        value: 0
      - value: 0
        type: Boolean
        name: Vote_less_diff_from_target_ratio
      - type: Boolean
        name: Vote_length
        value: 0
      - name: Vote_higher
        value: 0
        type: Boolean
      - type: String
        value: buoy
        name: ID
      - type: String
        name: spec1
        value: red
      - value: blue
        type: String
        name: spec2
      - type: Double
        name: Min_area
        value: 200.000000
      - value: 0.500000
        name: Ratio_target
        type: Double
      - value: 0.100000
        type: Double
        name: Diff_from_ratio_target
      - name: angle_target
        type: Double
        value: 0.000000
      - type: Double
        value: 30.000000
        name: Diff_from_angle_target
      - type: Double
        value: 50.000000
        name: Min_percent_filled
      - name: Contour_retreval
        value: 0
        type: Integer
    id: 6
    name: ObjectFinder